root: true

env:
  es6: true
  browser: true
  angular/angular: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    impliedStrict: true

plugins:
- angular

extends:
- eslint:recommended

rules:
  # can be fixed with --fix in CLI
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - never

  # https://github.com/Gillespie59/eslint-plugin-angular#rules
  # rules chosen with the assumption controllers are not used directly
  angular/avoid-scope-typos: 1
  angular/module-getter: 2
  angular/module-setter: 2
  angular/no-private-call: 2
  angular/deferred: 2
  angular/di-unused: 2
  angular/directive-restrict: 2
  angular/no-controller: 2
  angular/no-inline-template: 2
  angular/no-run-logic: 2
  angular/no-services:
    - 2
    -
      - http
      - resource
      - q
    -
      - directive
      - filter
  angular/on-watch: 2
  angular/prefer-component: 2
  angular/no-cookiestore: 2
  angular/no-directive-replace: 2
  angular/no-http-callback: 2
  angular/component-name:
    - 2
    - fl
  angular/constant-name:
    - 2
    - fl
  angular/directive-name:
    - 2
    - fl
  angular/factory-name:
    - 2
    - fl
  angular/filter-name:
    - 2
    - fl
  angular/provider-name:
    - 2
    - fl
  angular/value-name:
    - 2
    - fl
  angular/di-order: 2
  # check ngInject
  angular/di:
    - 2
    - array
  angular/function-type:
    - 2
    - named
  angular/module-dependency-order: 2
  angular/rest-service:
    - 2
    - http
  angular/watchers-execution:
    - 2
    - $digest
  angular/definedundefined: 2
  angular/document-service: 2
  angular/json-functions: 2
  angular/log: 2
  angular/typecheck-array: 2
  angular/typecheck-date: 2
  angular/typecheck-function: 2
  angular/typecheck-number: 2
  angular/typecheck-object: 2
  angular/typecheck-string: 2
  angular/window-service: 2
  angular/on-destroy: 2
